### ISSUE TITLE
Default namespace propagation to children of a child

### ISSUE THREAD

**Issue by asrenzo** [dapper91/pydantic-xml#202]
Hi,

Here is a simple test explaining a problem with a default namespace without an identifier.

```python
from datetime import datetime, timezone
from typing_extensions import Annotated
from pydantic import BeforeValidator, PlainSerializer
from pydantic_xml import BaseXmlModel, attr, element

XML = """<?xml version="1.0"?>
<Node1 xmlns="http://www.something.com/a/path/1.1" node1-id="20240722143302080ABCDEFGH" node1-date="2024-07-22 14:33:02,080" status="OK">
  <Node2>
    <Node3>Some value</Node3>
  </Node2>
</Node1>
"""

CustomDatetime = Annotated[
    datetime,
    BeforeValidator(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S,%f').astimezone(tz=timezone.utc)),
    PlainSerializer(lambda x: x.isoformat())
]

class Node3(BaseXmlModel):
    value: str


class Node2(BaseXmlModel):
    node3:Node3 = element(tag="Node3")


class Node1(BaseXmlModel, tag="Node1", ns="", nsmap={"": "http://www.something.com/a/path/1.1"}):
    node1_id: str = attr("node1-id")
    node1_date: CustomDatetime = attr("node1-date")
    status:str = attr("status")
    node2: Node2 = element(tag="Node2")


node1 = Node1.from_xml(XML)
print(node1.model_dump_json())
```

Trying to run this sample will end with an error because the default namespace sounds not to be propagated to children of children.

```bash
Traceback (most recent call last):
  File "sample.py", line 49, in <module>
    node1 = Node1.from_xml(XML)
            ^^^^^^^^^^^^^^^^^^^
  File "/test-managers-prnkWGdx-py3.11/lib/python3.11/site-packages/pydantic_xml/model.py", line 470, in from_xml
    return cls.from_xml_tree(etree.fromstring(source), context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/test-managers-prnkWGdx-py3.11/lib/python3.11/site-packages/pydantic_xml/model.py", line 447, in from_xml_tree
    ModelT, cls.__xml_serializer__.deserialize(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/test-managers-prnkWGdx-py3.11/lib/python3.11/site-packages/pydantic_xml/serializers/factories/model.py", line 201, in deserialize
    raise utils.build_validation_error(title=self._model.__name__, errors_map=field_errors)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Node1
node2.node3
  [line 3]: Field required [type=missing, input_value={}, input_type=dict]

```

The only way to get this sample to work is to manually add namespace infos to Node2 model.

```python
from datetime import datetime, timezone
from typing_extensions import Annotated
from pydantic import BeforeValidator, PlainSerializer
from pydantic_xml import BaseXmlModel, attr, element

XML = """<?xml version="1.0"?>
<Node1 xmlns="http://www.something.com/a/path/1.1" node1-id="20240722143302080ABCDEFGH" node1-date="2024-07-22 14:33:02,080" status="OK">
  <Node2>
    <Node3>Some value</Node3>
  </Node2>
</Node1>
"""

CustomDatetime = Annotated[
    datetime,
    BeforeValidator(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S,%f').astimezone(tz=timezone.utc)),
    PlainSerializer(lambda x: x.isoformat())
]

class Node3(BaseXmlModel):
    value: str


class Node2(BaseXmlModel, ns="", nsmap={"": "http://www.something.com/a/path/1.1"}):
    node3:Node3 = element(tag="Node3")


class Node1(BaseXmlModel, tag="Node1", ns="", nsmap={"": "http://www.something.com/a/path/1.1"}):
    node1_id: str = attr("node1-id")
    node1_date: CustomDatetime = attr("node1-date")
    status:str = attr("status")
    node2: Node2 = element(tag="Node2")


node1 = Node1.from_xml(XML)
print(node1.model_dump_json())
```
Did I miss something to force default namesapce propagation to all children elements ?

Because lxml will prefix every element with {"http://www.something.com/a/path/1.1"}

Hope I'm clear.

Regards,

Laurent

**Comment by dapper91** [comment]
@asrenzo Hi,

That is the intended behavior. The namespace map is not propagated to child elements, because the model serializer/deserializer is built during the model declaration and it doesn't know anything about its parent namespace. The only way to define is manually.

**Comment by asrenzo** [comment]
Ok THX for your answer
