### ISSUE TITLE
Order of model attributes affects parsing

### ISSUE THREAD

**Issue by karvetskiy** [dapper91/pydantic-xml#48]
Hello everyone.

After a few hours of debugging I realise, that order of attributes affects validation. It was really unexpected for me.
Is it specificity of working or I did something wrong?

I have root class
```
class InvoiceData(BaseXmlModel, tag="InvoiceData", ns="", nsmap=nsmap):
    invoice_number: str = element(tag="invoiceNumber")
    invoice_date: str = element(tag="invoiceIssueDate")
    completeness_indicator: bool = element(tag="completenessIndicator", default=False)
    invoice_main: InvoiceMain
```
and can normally parse XML file like this,
```
with open("test.xml", "r") as f:
    s = f.read().encode()
invoice_data = InvoiceData.from_xml(s)
print(invoice_data.dict())
```
```
{
    'invoice_number': '2021/00235', 
    'invoice_date': '2021-05-15', 
    'completeness_indicator': False, 
    'invoice_main': {...}
}
```

But when I change order of arguments
```
class InvoiceData(BaseXmlModel, tag="InvoiceData", ns="", nsmap=nsmap):
    invoice_number: str = element(tag="invoiceNumber")
    invoice_date: str = element(tag="invoiceIssueDate")
    invoice_main: InvoiceMain
    completeness_indicator: bool = element(tag="completenessIndicator", default=False)
```
It raise a ValidationError
```
Traceback (most recent call last):
  File "/Users/vsevolod/whoosh/a2-backend/src/Invoice/services/main/hungary/shared/test.py", line 7, in <module>
    invoice_data = InvoiceData.from_xml(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic_xml/model.py", line 286, in from_xml
    return cls.from_xml_tree(etree.fromstring(source))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic_xml/model.py", line 270, in from_xml_tree
    obj = cls.__xml_serializer__.deserialize(XmlElement.from_native(root))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic_xml/serializers/factories/model.py", line 86, in deserialize
    return self._model.parse_obj(obj)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for InvoiceData
invoice_main
  field required (type=value_error.missing)
```

Didn't have problems like this on simpler models. I think this is caused by some structure of nested models

**Comment by dapper91** [comment]
@karvetskiy Hi. 

That is the intended behavior. Parser respects fields order during binding by default. In case an element contains sub-elements that can be presented in any order, `BaseXmlModel` supports several [search strategies](https://pydantic-xml.readthedocs.io/en/latest/pages/data-binding/elements.html#elements-search-mode).
In your case you can use [unordered](https://pydantic-xml.readthedocs.io/en/latest/pages/data-binding/elements.html#unordered) search mode which searches for sub-elements despite field declaration order. Your model will be like this:

```python
class InvoiceData(BaseXmlModel, tag="InvoiceData", ns="", nsmap=nsmap, search_mode='unordered'):
    invoice_number: str = element(tag="invoiceNumber")
    invoice_date: str = element(tag="invoiceIssueDate")
    completeness_indicator: bool = element(tag="completenessIndicator", default=False)
    invoice_main: InvoiceMain
```

**Comment by karvetskiy** [comment]
@dapper91 That's exactly what I need. 
Missed this point in the documentation.
Thanks

**Comment by dapper91** [comment]
Are you sure your xml document is correct? I can't see where `base` namespace is defined.

**Comment by dapper91** [comment]
@karvetskiy Could you provide the full code? This works ok:

```python
from typing import Optional
from pydantic_xml import BaseXmlModel, element

xml = '''
<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:base="http://schemas.nav.gov.hu/OSA/3.0/base">
    <customerInfo>
        <customerVatStatus>DOMESTIC</customerVatStatus>
        <customerVatData>
            <customerTaxNumber>
                <base:taxpayerId>99887764</base:taxpayerId>
                <base:vatCode>2</base:vatCode>
                <base:countyCode>02</base:countyCode>
            </customerTaxNumber>
        </customerVatData>
        <customerName>Beszerző Kft</customerName>
        <customerAddress>
            <base:detailedAddress>
                <base:countryCode>HU</base:countryCode>
                <base:postalCode>7600</base:postalCode>
                <base:city>Pécs</base:city>
                <base:streetName>Északi</base:streetName>
                <base:publicPlaceCategory>sugárút</base:publicPlaceCategory>
                <base:number>123</base:number>
            </base:detailedAddress>
        </customerAddress>
    </customerInfo>
</InvoiceData>
'''

nsmap = {
    "": "http://schemas.nav.gov.hu/OSA/3.0/data",
    "base": "http://schemas.nav.gov.hu/OSA/3.0/base",
}

class CustomerTaxNumber(BaseXmlModel, tag="customerTaxNumber", ns="", nsmap=nsmap):
    taxpayer_id: str = element(tag="taxpayerId", ns="base", nsmap=nsmap)


class CustomerVatData(BaseXmlModel, tag="customerVatData", ns="", nsmap=nsmap):
    customer_tax_number: CustomerTaxNumber


class CustomerInfo(BaseXmlModel, tag="customerInfo", ns="", nsmap=nsmap, search_mode="unordered"):
    customer_vat_status: str = element(default='', tag="customerVatStatus")
    customer_vat_data: Optional[CustomerVatData]
    customer_name: Optional[str] = element(tag="customerName")


class InvoiceData(BaseXmlModel, tag='InvoiceData', ns="", nsmap=nsmap):
    customer_info: CustomerInfo

invoice = InvoiceData.from_xml(xml)

print(invoice)
```

output:
```text
customer_info=CustomerInfo(customer_vat_status='DOMESTIC', customer_vat_data=CustomerVatData(customer_tax_number=CustomerTaxNumber(taxpayer_id='99887764')), customer_name='Beszerző Kft')```

**Comment by karvetskiy** [comment]
Of course. I don't see diffs with my code...
```
class VatStatus(Enum):
    domestic = "DOMESTIC"
    private = "PRIVATE_PERSON"


class CustomerTaxNumber(BaseXmlModel, tag="customerTaxNumber", ns="", nsmap=nsmap):
    taxpayer_id: str = element(tag="taxpayerId", ns="base", nsmap=nsmap)


class CustomerVatData(BaseXmlModel, ns="", nsmap=nsmap, tag="customerVatData"):
    customer_tax_number: CustomerTaxNumber


class CustomerInfo(BaseXmlModel, tag="customerInfo", ns="", nsmap=nsmap, search_mode="unordered"):
    customer_vat_status: VatStatus = element(default=VatStatus.private, tag="customerVatStatus")
    customer_vat_data: Optional[CustomerVatData]
    customer_name: Optional[str] = element(tag="customerName")


class InvoiceHead(BaseXmlModel, tag="invoiceHead", ns="", nsmap=nsmap, search_mode="unordered"):
    customer_info: CustomerInfo


class Invoice(BaseXmlModel, tag="invoice", ns="", nsmap=nsmap, search_mode="unordered"):
    invoice_reference: Optional[InvoiceReference] = element(tag="invoiceReference")
    invoice_head: InvoiceHead = element(tag="invoiceHead")


class InvoiceMain(BaseXmlModel, tag="invoiceMain", ns="", nsmap=nsmap):
    invoice: Invoice


class InvoiceData(BaseXmlModel, tag="InvoiceData", ns="", nsmap=nsmap, search_mode="unordered"):
    invoice_number: str = element(tag="invoiceNumber")
    invoice_date: str = element(tag="invoiceIssueDate")
    completeness_indicator: bool = element(tag="completenessIndicator", default=False)
    invoice_main: InvoiceMain
    

with open("test.xml", "rb") as f:
    data = f.read()
invoice_data = InvoiceData.from_xml(data)
print(invoice_data)

```
This code has validationError on taxpayer_id field with this file (https://gist.github.com/karvetskiy/e427bd99a607db020e50a98a68a30425)

**Comment by dapper91** [comment]
@karvetskiy Hmm.. 

For the model you defined  namespace `base` as "http://schemas.nav.gov.hu/NTCA/1.0/base".
In the xml document xmlns:base="http://schemas.nav.gov.hu/OSA/3.0/base"

I think that the problem.

**Comment by karvetskiy** [comment]
@dapper91 Really...
It was broking my mind for a long time)
Non-obvious thing for me
Thank you so much for help!
